




Map:  99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▊ | 824/833 [00:24<00:00, 128.89 examples/s]Exception ignored in: <function _xla_gc_callback at 0x15c789a60>
Traceback (most recent call last):
  File "/Users/nicholasbardy/.pyenv/versions/3.9.9/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 103, in _xla_gc_callback
    def _xla_gc_callback(*args):
KeyboardInterrupt:
Exception ignored in: <function _xla_gc_callback at 0x15c789a60>
Traceback (most recent call last):
  File "/Users/nicholasbardy/.pyenv/versions/3.9.9/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 103, in _xla_gc_callback
    def _xla_gc_callback(*args):
KeyboardInterrupt:
Exception ignored in: <function _xla_gc_callback at 0x15c789a60>
Traceback (most recent call last):
  File "/Users/nicholasbardy/.pyenv/versions/3.9.9/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 103, in _xla_gc_callback
    def _xla_gc_callback(*args):
KeyboardInterrupt:
Exception ignored in: <function _xla_gc_callback at 0x15c789a60>
Traceback (most recent call last):
  File "/Users/nicholasbardy/.pyenv/versions/3.9.9/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 103, in _xla_gc_callback
    def _xla_gc_callback(*args):
KeyboardInterrupt:
Exception ignored in: <function _xla_gc_callback at 0x15c789a60>
Traceback (most recent call last):
  File "/Users/nicholasbardy/.pyenv/versions/3.9.9/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 103, in _xla_gc_callback
    def _xla_gc_callback(*args):
KeyboardInterrupt:
Exception ignored in: <function _xla_gc_callback at 0x15c789a60>
Traceback (most recent call last):
  File "/Users/nicholasbardy/.pyenv/versions/3.9.9/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 103, in _xla_gc_callback
    def _xla_gc_callback(*args):
KeyboardInterrupt:
Exception ignored in: <function _xla_gc_callback at 0x15c789a60>
Traceback (most recent call last):
  File "/Users/nicholasbardy/.pyenv/versions/3.9.9/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 103, in _xla_gc_callback
    def _xla_gc_callback(*args):
KeyboardInterrupt:
Exception ignored in: <function _xla_gc_callback at 0x15c789a60>
Traceback (most recent call last):
  File "/Users/nicholasbardy/.pyenv/versions/3.9.9/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 103, in _xla_gc_callback
    def _xla_gc_callback(*args):
KeyboardInterrupt:
Exception ignored in: <function _xla_gc_callback at 0x15c789a60>
Traceback (most recent call last):
  File "/Users/nicholasbardy/.pyenv/versions/3.9.9/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 103, in _xla_gc_callback
    def _xla_gc_callback(*args):
KeyboardInterrupt:
Exception ignored in: <function _xla_gc_callback at 0x15c789a60>
Traceback (most recent call last):
  File "/Users/nicholasbardy/.pyenv/versions/3.9.9/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 103, in _xla_gc_callback
    def _xla_gc_callback(*args):
KeyboardInterrupt:
Exception ignored in: <function _xla_gc_callback at 0x15c789a60>
Traceback (most recent call last):
  File "/Users/nicholasbardy/.pyenv/versions/3.9.9/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 103, in _xla_gc_callback
    def _xla_gc_callback(*args):
KeyboardInterrupt:
Exception ignored in: <function _xla_gc_callback at 0x15c789a60>
Traceback (most recent call last):
  File "/Users/nicholasbardy/.pyenv/versions/3.9.9/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 103, in _xla_gc_callback
    def _xla_gc_callback(*args):
KeyboardInterrupt:
Exception ignored in: <function _xla_gc_callback at 0x15c789a60>
Traceback (most recent call last):
  File "/Users/nicholasbardy/.pyenv/versions/3.9.9/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 103, in _xla_gc_callback
    def _xla_gc_callback(*args):
KeyboardInterrupt:
Exception ignored in: <function _xla_gc_callback at 0x15c789a60>
Traceback (most recent call last):
  File "/Users/nicholasbardy/.pyenv/versions/3.9.9/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 103, in _xla_gc_callback
    def _xla_gc_callback(*args):
KeyboardInterrupt:
Exception ignored in: <function _xla_gc_callback at 0x15c789a60>
Traceback (most recent call last):
  File "/Users/nicholasbardy/.pyenv/versions/3.9.9/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 103, in _xla_gc_callback
    def _xla_gc_callback(*args):
KeyboardInterrupt:
Exception ignored in: <function _xla_gc_callback at 0x15c789a60>
Traceback (most recent call last):
  File "/Users/nicholasbardy/.pyenv/versions/3.9.9/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 103, in _xla_gc_callback
    def _xla_gc_callback(*args):
KeyboardInterrupt:
Exception ignored in: <function _xla_gc_callback at 0x15c789a60>
Traceback (most recent call last):
  File "/Users/nicholasbardy/.pyenv/versions/3.9.9/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 103, in _xla_gc_callback
    def _xla_gc_callback(*args):
